packages:
  - 'packages/*'
  - 'packages/primitives/*'
  - 'packages/advanced/*'
  - 'benchmarks/*'
  - 'apps/*'
  - 'examples/*'

allowBuilds:
  esbuild: true
  simple-git-hooks: true

overrides:
  chokidar: 4.0.2
  vue: 3.5.38
