import type {
  ZeusWebAiComponent,
  ZeusWebAiMetadata,
} from '../../packages/ai/src'
import type { Registry, RegistryItem } from '../../packages/registry/src'

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { aiMetadata, validateAiMetadata } from '../../packages/ai/src'

export interface ComponentDocsContext {
  metadata: ZeusWebAiMetadata
  registry: Registry
}

export interface GeneratedDoc {
  path: string
  content: string
}

const generatedHeader = `<!-- This file is generated by scripts/commands/generate-docs.ts. Do not edit manually. -->`

export function loadRegistry(root = process.cwd()): Registry {
  return JSON.parse(
    readFileSync(resolve(root, 'packages/registry/registry.json'), 'utf-8'),
  ) as Registry
}

export function createComponentDocsContext(
  root = process.cwd(),
): ComponentDocsContext {
  const result = validateAiMetadata(aiMetadata)

  if (!result.valid) {
    throw new Error(
      [
        'Invalid @zeus-web/ai metadata:',
        ...result.errors.map(error => `- ${error}`),
      ].join('\n'),
    )
  }

  return {
    metadata: aiMetadata,
    registry: loadRegistry(root),
  }
}

function findRegistryItem(
  registry: Registry,
  component: ZeusWebAiComponent,
): RegistryItem | undefined {
  return registry.items.find(item => item.name === component.name)
}

function mdInlineCode(value: string): string {
  return `\`${value.replace(/`/g, '\\`')}\``
}

function mdCodeBlock(language: string, code: string): string {
  return [`\`\`\`${language}`, code, '```'].join('\n')
}

function renderStringList(items: string[]): string {
  if (items.length === 0) {
    return '- None.'
  }

  return items.map(item => `- ${item}`).join('\n')
}

function renderCodeList(items: string[]): string {
  if (items.length === 0) {
    return '- None.'
  }

  return items.map(item => `- ${mdInlineCode(item)}`).join('\n')
}

function renderPropsTable(component: ZeusWebAiComponent): string {
  if (component.props.length === 0) {
    return 'No public props documented.'
  }

  return [
    '| Prop | Type | Default | Description |',
    '| --- | --- | --- | --- |',
    ...component.props.map(prop => {
      const type = mdInlineCode(prop.type)
      const values = prop.values?.length
        ? `<br />Values: ${prop.values.map(mdInlineCode).join(', ')}`
        : ''
      const defaultValue = prop.default ? mdInlineCode(prop.default) : '-'

      return `| ${mdInlineCode(prop.name)} | ${type}${values} | ${defaultValue} | ${prop.description} |`
    }),
  ].join('\n')
}

function renderEventsTable(component: ZeusWebAiComponent): string {
  if (component.events.length === 0) {
    return 'No public events documented.'
  }

  return [
    '| Event | React prop | Detail | Description |',
    '| --- | --- | --- | --- |',
    ...component.events.map(event => {
      const detail = Object.entries(event.detail)
        .map(([key, value]) => `${key}: ${value}`)
        .join(', ')

      return `| ${mdInlineCode(event.name)} | ${mdInlineCode(event.reactName)} | ${mdInlineCode(detail)} | ${event.description} |`
    }),
  ].join('\n')
}

function renderSlotsTable(component: ZeusWebAiComponent): string {
  if (component.slots.length === 0) {
    return 'No slots documented.'
  }

  return [
    '| Slot | Description |',
    '| --- | --- |',
    ...component.slots.map(slot => {
      return `| ${mdInlineCode(slot.name)} | ${slot.description} |`
    }),
  ].join('\n')
}

function renderExamples(component: ZeusWebAiComponent): string {
  if (component.examples.length === 0) {
    return 'No examples documented.'
  }

  return component.examples
    .map(example => {
      return [
        `### ${example.title}`,
        '',
        mdCodeBlock('tsx', example.code),
      ].join('\n')
    })
    .join('\n\n')
}

function renderRegistryInfo(
  component: ZeusWebAiComponent,
  registryItem?: RegistryItem,
): string {
  if (!registryItem) {
    return [
      '## Registry',
      '',
      `Registry item for ${mdInlineCode(component.name)} was not found.`,
    ].join('\n')
  }

  return [
    '## Registry',
    '',
    `Type: ${mdInlineCode(registryItem.type)}`,
    '',
    'Dependencies:',
    '',
    renderCodeList(registryItem.dependencies ?? []),
    '',
    'Files:',
    '',
    registryItem.files.length === 0
      ? '- None.'
      : registryItem.files
          .map(file => {
            return `- ${mdInlineCode(file.source)} \u2192 ${mdInlineCode(file.target)}`
          })
          .join('\n'),
  ].join('\n')
}

export function renderComponentDoc(
  component: ZeusWebAiComponent,
  registryItem?: RegistryItem,
): string {
  return [
    generatedHeader,
    '',
    `# ${component.name[0].toUpperCase()}${component.name.slice(1)}`,
    '',
    component.description,
    '',
    '<div class="zw-badge-row">',
    `  <span class="zw-badge">${component.primitivePackage}</span>`,
    `  <span class="zw-badge">${component.registryCommand}</span>`,
    '  <span class="zw-badge">Generated</span>',
    '</div>',
    '',
    '## Add',
    '',
    mdCodeBlock('bash', component.registryCommand),
    '',
    '## Imports',
    '',
    'Styled component:',
    '',
    mdCodeBlock('tsx', component.styledImport),
    '',
    'Primitive React wrapper:',
    '',
    mdCodeBlock('tsx', component.reactImport),
    '',
    'Web Component entry:',
    '',
    mdCodeBlock('ts', component.webComponentImport),
    '',
    '## Props',
    '',
    renderPropsTable(component),
    '',
    '## Events',
    '',
    renderEventsTable(component),
    '',
    '## Slots',
    '',
    renderSlotsTable(component),
    '',
    '## Styling',
    '',
    `Uses Tailwind: ${component.styling.usesTailwind ? 'yes' : 'no'}`,
    '',
    'Theme tokens:',
    '',
    renderCodeList(component.styling.themeTokens),
    '',
    'Internal selectors:',
    '',
    renderCodeList(component.styling.internalSelectors),
    '',
    renderRegistryInfo(component, registryItem),
    '',
    '## AI usage rules',
    '',
    'Do:',
    '',
    renderStringList(component.aiRules.do),
    '',
    'Do not:',
    '',
    renderStringList(component.aiRules.dont),
    '',
    '## Examples',
    '',
    renderExamples(component),
    '',
  ].join('\n')
}

export function renderComponentsIndex(context: ComponentDocsContext): string {
  return [
    generatedHeader,
    '',
    '# Components',
    '',
    'This section is generated from `@zeus-web/ai` metadata and `@zeus-web/registry`.',
    '',
    '| Component | Package | Add command | Description |',
    '| --- | --- | --- | --- |',
    ...context.metadata.components.map(component => {
      return `| [${component.name}](/components/${component.name}) | ${mdInlineCode(component.primitivePackage)} | ${mdInlineCode(component.registryCommand)} | ${component.description} |`
    }),
    '',
    '## Recommended workflow',
    '',
    renderStringList(context.metadata.recommendedWorkflow),
    '',
  ].join('\n')
}

export function generateComponentDocs(
  context = createComponentDocsContext(),
): GeneratedDoc[] {
  const docs: GeneratedDoc[] = [
    {
      path: 'apps/docs/components/index.md',
      content: renderComponentsIndex(context),
    },
  ]

  for (const component of context.metadata.components) {
    const registryItem = findRegistryItem(context.registry, component)

    if (!registryItem) continue

    docs.push({
      path: `apps/docs/components/${component.name}.md`,
      content: renderComponentDoc(component, registryItem),
    })
  }

  return docs
}
