import type {
  ComponentCatalogItem,
  ComponentName,
} from '../../apps/docs/.vitepress/data/component-catalog'
import type { DocsLocale } from '../../apps/docs/.vitepress/data/docs-i18n'
import type {
  ZeusWebAiComponent,
  ZeusWebAiMetadata,
} from '../../packages/ai/src'
import type { Registry, RegistryItem } from '../../packages/registry/src'

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import {
  findComponentCatalogItem,
  getComponentCatalog,
  getComponentCategories,
  localizeDocsPath,
} from '../../apps/docs/.vitepress/data/component-catalog'
import {
  defaultDocsLocale,
  docsLocaleIds,
} from '../../apps/docs/.vitepress/data/docs-i18n'
import { playgroundSources } from '../../apps/docs/.vitepress/data/playground-sources'
import { aiMetadata, validateAiMetadata } from '../../packages/ai/src'
import {
  getAdvancedDocsTranslation,
  getComponentDocsMessages,
  normalizeAdvancedExampleCode,
  translatePrimitiveDocsText,
  translateRecommendedWorkflow,
} from './component-docs-i18n'
import { renderEmbeddedPlayground } from './playground-docs'

export interface ComponentDocsContext {
  metadata: ZeusWebAiMetadata
  registry: Registry
}

export interface GeneratedDoc {
  path: string
  content: string
}

type ZeusWebAiAdvancedComponent =
  ZeusWebAiMetadata['advancedComponents'][number]

const generatedHeader =
  '<!-- This file is generated by scripts/commands/generate-docs.ts. Do not edit manually. -->'

function getCatalogItem(
  name: string,
  locale: DocsLocale,
): ComponentCatalogItem {
  const item = findComponentCatalogItem(name, locale)

  if (!item) {
    throw new Error(`Missing component catalog entry for "${name}".`)
  }

  return item
}

function getCategoryTitle(
  component: ComponentCatalogItem,
  locale: DocsLocale,
): string {
  const category = getComponentCategories(locale).find(
    item => item.id === component.category,
  )

  if (!category) {
    throw new Error(
      `Missing component category "${component.category}" for ${component.packageName}.`,
    )
  }

  return category.label
}

function renderPageFrontmatter(component: ComponentCatalogItem): string {
  if (component.name === 'data-grid') {
    return [
      '---',
      'aside: false',
      'pageClass: component-docs-page data-grid-playground-page',
      '---',
    ].join('\n')
  }

  return ['---', 'pageClass: component-docs-page', '---'].join('\n')
}

function renderCatalogBadges(
  component: ComponentCatalogItem,
  labels: string[],
  locale: DocsLocale,
): string {
  return [
    '<div class="zw-badge-row">',
    `  <span class="zw-badge">${component.packageName}</span>`,
    `  <span class="zw-badge">${getCategoryTitle(component, locale)}</span>`,
    ...labels.map(label => `  <span class="zw-badge">${label}</span>`),
    '</div>',
  ].join('\n')
}

function renderCatalogPlayground(
  component: ComponentCatalogItem,
  root = process.cwd(),
  locale: DocsLocale = defaultDocsLocale,
): string {
  const sources = playgroundSources[component.name as ComponentName]

  return renderEmbeddedPlayground(component, sources, locale, root)
}

export function loadRegistry(root = process.cwd()): Registry {
  return JSON.parse(
    readFileSync(resolve(root, 'packages/registry/registry.json'), 'utf-8'),
  ) as Registry
}

export function createComponentDocsContext(
  root = process.cwd(),
): ComponentDocsContext {
  const result = validateAiMetadata(aiMetadata)

  if (!result.valid) {
    throw new Error(
      [
        'Invalid @zeus-web/ai metadata:',
        ...result.errors.map(error => `- ${error}`),
      ].join('\n'),
    )
  }

  return {
    metadata: aiMetadata,
    registry: loadRegistry(root),
  }
}

function findRegistryItem(
  registry: Registry,
  component: ZeusWebAiComponent,
): RegistryItem | undefined {
  return registry.items.find(
    item => item.type === 'component' && item.name === component.name,
  )
}

function requireRegistryValue(
  component: ZeusWebAiComponent,
  field: 'registryCommand' | 'styledImport',
): string {
  const value = component[field]

  if (!value) {
    throw new Error(
      `${component.name} is present in the Registry manifest but AI metadata is missing ${field}.`,
    )
  }

  return value
}

function isRegistryComponent(
  registry: Registry,
  component: ZeusWebAiComponent,
): boolean {
  return Boolean(findRegistryItem(registry, component))
}

function mdInlineCode(value: string): string {
  return `\`${value.replace(/`/g, '\\`')}\``
}

function renderInlineElementTag(value: string): string {
  return mdInlineCode(value)
}

function renderMarkdownText(value: string): string {
  return value
    .split(/(`[^`]*`)/g)
    .map((segment, index) => {
      if (index % 2 === 1) return segment

      return segment.replace(/<\/?[a-z][a-z0-9-]*>/gi, renderInlineElementTag)
    })
    .join('')
}

function mdCodeBlock(language: string, code: string): string {
  return [`\`\`\`${language}`, code, '```'].join('\n')
}

function renderStringList(items: string[], emptyText = 'None.'): string {
  if (items.length === 0) return `- ${emptyText}`
  return items.map(item => `- ${renderMarkdownText(item)}`).join('\n')
}

function renderCodeList(items: string[], emptyText = 'None.'): string {
  if (items.length === 0) return `- ${emptyText}`
  return items.map(item => `- ${mdInlineCode(item)}`).join('\n')
}

function renderPropsTable(
  component: ZeusWebAiComponent,
  locale: DocsLocale,
): string {
  const messages = getComponentDocsMessages(locale)
  if (component.props.length === 0) return messages.noPublicProps
  const [propHeader, typeHeader, defaultHeader, descriptionHeader] =
    messages.propTableHeaders

  return [
    `| ${propHeader} | ${typeHeader} | ${defaultHeader} | ${descriptionHeader} |`,
    '| --- | --- | --- | --- |',
    ...component.props.map(prop => {
      const type = mdInlineCode(prop.type)
      const values =
        prop.values && prop.values.length
          ? `<br />${messages.valuesLabel}: ${prop.values.map(mdInlineCode).join(', ')}`
          : ''
      const defaultValue = prop.default ? mdInlineCode(prop.default) : '-'

      const description = translatePrimitiveDocsText(prop.description, locale)

      return `| ${mdInlineCode(prop.name)} | ${type}${values} | ${defaultValue} | ${description} |`
    }),
  ].join('\n')
}

function renderEventsTable(
  component: ZeusWebAiComponent,
  locale: DocsLocale,
): string {
  const messages = getComponentDocsMessages(locale)
  if (component.events.length === 0) return messages.noPublicEvents
  const [eventHeader, reactHeader, detailHeader, descriptionHeader] =
    messages.eventTableHeaders

  return [
    `| ${eventHeader} | ${reactHeader} | ${detailHeader} | ${descriptionHeader} |`,
    '| --- | --- | --- | --- |',
    ...component.events.map(event => {
      const detail = Object.entries(event.detail)
        .map(([key, value]) => `${key}: ${value}`)
        .join(', ')

      const description = translatePrimitiveDocsText(event.description, locale)

      return `| ${mdInlineCode(event.name)} | ${mdInlineCode(event.reactName)} | ${mdInlineCode(detail)} | ${description} |`
    }),
  ].join('\n')
}

function renderSlotsTable(
  component: ZeusWebAiComponent,
  locale: DocsLocale,
): string {
  const messages = getComponentDocsMessages(locale)
  if (component.slots.length === 0) return messages.noSlots
  const [slotHeader, descriptionHeader] = messages.slotTableHeaders

  return [
    `| ${slotHeader} | ${descriptionHeader} |`,
    '| --- | --- |',
    ...component.slots.map(slot => {
      return `| ${mdInlineCode(slot.name)} | ${translatePrimitiveDocsText(slot.description, locale)} |`
    }),
  ].join('\n')
}

function renderExamples(
  component: ZeusWebAiComponent,
  registryItem: RegistryItem | undefined,
  locale: DocsLocale,
): string {
  const messages = getComponentDocsMessages(locale)
  const examples = registryItem
    ? component.examples
    : component.examples.filter(
        example => !example.code.includes('@/components/ui/'),
      )

  if (examples.length === 0) return messages.noExamples

  return examples
    .map(example => {
      return [
        `### ${translatePrimitiveDocsText(example.title, locale)}`,
        '',
        mdCodeBlock('tsx', example.code),
      ].join('\n')
    })
    .join('\n\n')
}

function renderRegistryStatus(
  component: ZeusWebAiComponent,
  registryItem?: RegistryItem,
  locale: DocsLocale = defaultDocsLocale,
): string {
  const messages = getComponentDocsMessages(locale)

  if (!registryItem) {
    return [
      `## ${messages.registry}`,
      '',
      messages.registryUnavailable,
      '',
      messages.registryUnavailableDescription(
        component.name,
        component.primitivePackage,
      ),
      '',
      messages.registryUnavailableAction,
    ].join('\n')
  }

  return [
    `## ${messages.registry}`,
    '',
    messages.registryAvailable,
    '',
    `${messages.addCommand}: ${mdInlineCode(
      requireRegistryValue(component, 'registryCommand'),
    )}`,
    '',
    `${messages.type}: ${mdInlineCode(registryItem.type)}`,
    '',
    messages.dependencies,
    '',
    renderCodeList(registryItem.dependencies || [], messages.noPublicMembers),
    '',
    messages.registryDependencies,
    '',
    renderCodeList(
      registryItem.registryDependencies || [],
      messages.noPublicMembers,
    ),
    '',
    messages.files,
    '',
    registryItem.files.length === 0
      ? `- ${messages.noPublicMembers}`
      : registryItem.files
          .map(file => {
            return `- ${mdInlineCode(file.source)} → ${mdInlineCode(file.target)}`
          })
          .join('\n'),
  ].join('\n')
}

function renderAddSection(
  component: ZeusWebAiComponent,
  registryItem?: RegistryItem,
  locale: DocsLocale = defaultDocsLocale,
): string {
  const messages = getComponentDocsMessages(locale)

  if (!registryItem) {
    return [
      `## ${messages.install}`,
      '',
      messages.installMissingRegistry,
      '',
      messages.installPrimitiveInstead,
      '',
      mdCodeBlock('bash', `pnpm add ${component.primitivePackage}`),
    ].join('\n')
  }

  return [
    `## ${messages.add}`,
    '',
    mdCodeBlock('bash', requireRegistryValue(component, 'registryCommand')),
  ].join('\n')
}

function renderImportsSection(
  component: ZeusWebAiComponent,
  registryItem?: RegistryItem,
  locale: DocsLocale = defaultDocsLocale,
): string {
  const messages = getComponentDocsMessages(locale)
  const lines = [`## ${messages.imports}`, '']

  if (registryItem) {
    lines.push(
      messages.styledRegistryComponent,
      '',
      mdCodeBlock('tsx', requireRegistryValue(component, 'styledImport')),
      '',
    )
  } else {
    lines.push(
      messages.styledRegistryComponent,
      '',
      messages.notAvailableYet,
      '',
    )
  }

  lines.push(
    messages.primitiveReactWrapper,
    '',
    mdCodeBlock('tsx', component.reactImport),
    '',
    messages.webComponentEntry,
    '',
    mdCodeBlock('ts', component.webComponentImport),
  )

  return lines.join('\n')
}

export function renderComponentDoc(
  component: ZeusWebAiComponent,
  registryItem?: RegistryItem,
  root = process.cwd(),
  locale: DocsLocale = defaultDocsLocale,
): string {
  const catalogItem = getCatalogItem(component.name, locale)
  const messages = getComponentDocsMessages(locale)

  return [
    renderPageFrontmatter(catalogItem),
    '',
    generatedHeader,
    '',
    `# ${catalogItem.title}`,
    '',
    translatePrimitiveDocsText(component.description, locale),
    '',
    renderCatalogBadges(
      catalogItem,
      [
        registryItem
          ? requireRegistryValue(component, 'registryCommand')
          : messages.primitiveOnly,
        messages.generated,
      ],
      locale,
    ),
    '',
    renderCatalogPlayground(catalogItem, root, locale),
    '',
    renderAddSection(component, registryItem, locale),
    '',
    renderImportsSection(component, registryItem, locale),
    '',
    `## ${messages.props}`,
    '',
    renderPropsTable(component, locale),
    '',
    `## ${messages.events}`,
    '',
    renderEventsTable(component, locale),
    '',
    `## ${messages.slots}`,
    '',
    renderSlotsTable(component, locale),
    '',
    `## ${messages.styling}`,
    '',
    `${messages.usesTailwind}: ${
      component.styling.usesTailwind ? messages.yes : messages.no
    }`,
    '',
    messages.themeTokens,
    '',
    renderCodeList(component.styling.themeTokens, messages.noPublicMembers),
    '',
    messages.internalSelectors,
    '',
    renderCodeList(
      component.styling.internalSelectors,
      messages.noPublicMembers,
    ),
    '',
    renderRegistryStatus(component, registryItem, locale),
    '',
    `## ${messages.aiUsageRules}`,
    '',
    messages.do,
    '',
    renderStringList(
      component.aiRules.do.map(item =>
        translatePrimitiveDocsText(item, locale),
      ),
      messages.noPublicMembers,
    ),
    '',
    messages.doNot,
    '',
    renderStringList(
      component.aiRules.dont.map(item =>
        translatePrimitiveDocsText(item, locale),
      ),
      messages.noPublicMembers,
    ),
    '',
    `## ${messages.examples}`,
    '',
    renderExamples(component, registryItem, locale),
    '',
  ].join('\n')
}

function renderAdvancedMembers(
  title: string,
  members: Record<string, string[]> | undefined,
  locale: DocsLocale,
): string {
  const messages = getComponentDocsMessages(locale)
  const entries = Object.entries(members || {})

  if (entries.length === 0) {
    return [`## ${title}`, '', messages.noPublicMembers].join('\n')
  }

  return [
    `## ${title}`,
    '',
    ...entries.flatMap(([tagName, names]) => [
      `### ${mdInlineCode(tagName)}`,
      '',
      renderCodeList(names, messages.noPublicMembers),
      '',
    ]),
  ].join('\n')
}

function getAdvancedExampleLanguage(title: string): string {
  if (title.includes('React')) return 'tsx'
  return 'ts'
}

function renderAdvancedExamples(
  examples: ZeusWebAiAdvancedComponent['examples'],
  componentName: string,
  locale: DocsLocale,
): string {
  const messages = getComponentDocsMessages(locale)
  const translated = getAdvancedDocsTranslation(componentName, locale)

  if (examples.length !== translated.examples.length) {
    throw new Error(
      `${componentName} ${locale} advanced example documentation must contain ${examples.length} entries.`,
    )
  }

  if (examples.length === 0) {
    return [`## ${messages.examples}`, '', messages.noUsageExamples].join('\n')
  }

  return [
    `## ${messages.examples}`,
    '',
    ...examples.flatMap((example, index) => {
      const localizedExample = translated.examples[index]

      if (!localizedExample) {
        throw new Error(
          `Missing ${locale} advanced example documentation for ${componentName} example ${index}.`,
        )
      }

      return [
        `### ${localizedExample.title}`,
        '',
        renderMarkdownText(localizedExample.description),
        '',
        mdCodeBlock(
          getAdvancedExampleLanguage(example.title),
          normalizeAdvancedExampleCode(example.code),
        ),
        '',
      ]
    }),
  ].join('\n')
}

export function renderAdvancedComponentDoc(
  component: ComponentCatalogItem,
  metadata?: ZeusWebAiAdvancedComponent,
  root = process.cwd(),
  locale: DocsLocale = defaultDocsLocale,
): string {
  const localizedComponent = getCatalogItem(component.name, locale)
  const messages = getComponentDocsMessages(locale)
  const translated = getAdvancedDocsTranslation(component.name, locale)

  return [
    renderPageFrontmatter(localizedComponent),
    '',
    generatedHeader,
    '',
    `# ${localizedComponent.title}`,
    '',
    renderMarkdownText(translated.summary),
    '',
    renderCatalogBadges(localizedComponent, [messages.generated], locale),
    '',
    renderCatalogPlayground(localizedComponent, root, locale),
    '',
    `## ${messages.whenToUse}`,
    '',
    renderStringList(translated.whenToUse, messages.noPublicMembers),
    '',
    `## ${messages.whenNotToUse}`,
    '',
    renderStringList(translated.doNotUseFor, messages.noPublicMembers),
    '',
    `## ${messages.install}`,
    '',
    mdCodeBlock('bash', `pnpm add ${localizedComponent.packageName}`),
    '',
    `## ${messages.componentFamily}`,
    '',
    renderCodeList(
      metadata ? metadata.components : [],
      messages.noPublicMembers,
    ),
    '',
    renderAdvancedMembers(
      messages.slots,
      metadata ? metadata.slots : undefined,
      locale,
    ),
    '',
    renderAdvancedMembers(
      messages.events,
      metadata ? metadata.events : undefined,
      locale,
    ),
    '',
    renderAdvancedMembers(
      messages.methods,
      metadata ? metadata.methods : undefined,
      locale,
    ),
    '',
    renderAdvancedExamples(
      metadata ? metadata.examples : [],
      component.name,
      locale,
    ),
    '',
    `## ${messages.aiUsageHints}`,
    '',
    renderStringList(translated.promptHints, messages.noPublicMembers),
    '',
  ].join('\n')
}

export function renderComponentsIndex(
  context: ComponentDocsContext,
  locale: DocsLocale = defaultDocsLocale,
): string {
  const messages = getComponentDocsMessages(locale)
  const catalog = getComponentCatalog(locale)

  return [
    generatedHeader,
    '',
    `# ${messages.componentsTitle}`,
    '',
    messages.componentsDescription(catalog.length),
    '',
    '<ComponentDirectory />',
    '',
    `## ${messages.recommendedWorkflow}`,
    '',
    renderStringList(
      context.metadata.recommendedWorkflow.map(item =>
        translateRecommendedWorkflow(item, locale),
      ),
      messages.noPublicMembers,
    ),
    '',
    `## ${messages.currentRegistryComponents}`,
    '',
    renderCodeList(
      context.metadata.components
        .filter(component => isRegistryComponent(context.registry, component))
        .map(component => component.name),
      messages.noPublicMembers,
    ),
    '',
    messages.registryIndexDescription,
    '',
  ].join('\n')
}

function getGeneratedDocPath(route: string, locale: DocsLocale): string {
  const localizedRoute = localizeDocsPath(route, locale)
  const markdownPath = localizedRoute.endsWith('/')
    ? `${localizedRoute}index.md`
    : `${localizedRoute}.md`

  return `apps/docs${markdownPath}`
}

export function generateComponentDocs(
  context = createComponentDocsContext(),
  root = process.cwd(),
): GeneratedDoc[] {
  const docs: GeneratedDoc[] = []
  const primitiveByName = new Map<ComponentName, ZeusWebAiComponent>(
    context.metadata.components.map(component => [component.name, component]),
  )
  const advancedByName = new Map<ComponentName, ZeusWebAiAdvancedComponent>(
    context.metadata.advancedComponents.map(component => [
      component.name,
      component,
    ]),
  )

  for (const locale of docsLocaleIds) {
    const catalog = getComponentCatalog(locale)

    docs.push({
      path: getGeneratedDocPath('/components/', locale),
      content: renderComponentsIndex(context, locale),
    })

    for (const catalogItem of catalog) {
      if (catalogItem.packageGroup === 'primitives') {
        const primitive = primitiveByName.get(catalogItem.name)

        if (!primitive) {
          throw new Error(
            `Missing primitive AI metadata for ${catalogItem.packageName}.`,
          )
        }

        const registryItem = findRegistryItem(context.registry, primitive)

        docs.push({
          path: getGeneratedDocPath(`/components/${catalogItem.name}`, locale),
          content: renderComponentDoc(primitive, registryItem, root, locale),
        })
        continue
      }

      const advanced = advancedByName.get(catalogItem.name)

      if (!advanced) {
        throw new Error(
          `Missing advanced AI metadata for ${catalogItem.packageName}.`,
        )
      }

      docs.push({
        path: getGeneratedDocPath(`/components/${catalogItem.name}`, locale),
        content: renderAdvancedComponentDoc(
          catalogItem,
          advanced,
          root,
          locale,
        ),
      })
    }
  }

  return docs
}
