import type {
  ComponentCatalogItem,
  ComponentName,
} from '../../apps/docs/.vitepress/data/component-catalog'
import type {
  ZeusWebAiComponent,
  ZeusWebAiMetadata,
} from '../../packages/ai/src'
import type { Registry, RegistryItem } from '../../packages/registry/src'

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import {
  componentCatalog,
  componentCategories,
  findComponentCatalogItem,
} from '../../apps/docs/.vitepress/data/component-catalog'
import { playgroundSources } from '../../apps/docs/.vitepress/data/playground-sources'
import { aiMetadata, validateAiMetadata } from '../../packages/ai/src'
import { renderEmbeddedPlayground } from './playground-docs'

export interface ComponentDocsContext {
  metadata: ZeusWebAiMetadata
  registry: Registry
}

export interface GeneratedDoc {
  path: string
  content: string
}

type ZeusWebAiAdvancedComponent =
  ZeusWebAiMetadata['advancedComponents'][number]

const generatedHeader =
  '<!-- This file is generated by scripts/commands/generate-docs.ts. Do not edit manually. -->'

function getCatalogItem(name: string): ComponentCatalogItem {
  const item = findComponentCatalogItem(name)

  if (!item) {
    throw new Error(`Missing component catalog entry for "${name}".`)
  }

  return item
}

function getCategoryTitle(component: ComponentCatalogItem): string {
  const category = componentCategories.find(
    item => item.id === component.category,
  )

  if (!category) {
    throw new Error(
      `Missing component category "${component.category}" for ${component.packageName}.`,
    )
  }

  return category.label
}

function renderPageFrontmatter(component: ComponentCatalogItem): string {
  if (component.name === 'data-grid') {
    return [
      '---',
      'aside: false',
      'pageClass: component-docs-page data-grid-playground-page',
      '---',
    ].join('\n')
  }

  return ['---', 'pageClass: component-docs-page', '---'].join('\n')
}

function renderCatalogBadges(
  component: ComponentCatalogItem,
  labels: string[],
): string {
  return [
    '<div class="zw-badge-row">',
    `  <span class="zw-badge">${component.packageName}</span>`,
    `  <span class="zw-badge">${getCategoryTitle(component)}</span>`,
    ...labels.map(label => `  <span class="zw-badge">${label}</span>`),
    '</div>',
  ].join('\n')
}

function renderCatalogPlayground(
  component: ComponentCatalogItem,
  root = process.cwd(),
): string {
  const sources = playgroundSources[component.name as ComponentName]

  return renderEmbeddedPlayground(component, sources, root)
}

export function loadRegistry(root = process.cwd()): Registry {
  return JSON.parse(
    readFileSync(resolve(root, 'packages/registry/registry.json'), 'utf-8'),
  ) as Registry
}

export function createComponentDocsContext(
  root = process.cwd(),
): ComponentDocsContext {
  const result = validateAiMetadata(aiMetadata)

  if (!result.valid) {
    throw new Error(
      [
        'Invalid @zeus-web/ai metadata:',
        ...result.errors.map(error => `- ${error}`),
      ].join('\n'),
    )
  }

  return {
    metadata: aiMetadata,
    registry: loadRegistry(root),
  }
}

function findRegistryItem(
  registry: Registry,
  component: ZeusWebAiComponent,
): RegistryItem | undefined {
  return registry.items.find(
    item => item.type === 'component' && item.name === component.name,
  )
}

function isRegistryComponent(
  registry: Registry,
  component: ZeusWebAiComponent,
): boolean {
  return Boolean(findRegistryItem(registry, component))
}

function mdInlineCode(value: string): string {
  return `\`${value.replace(/`/g, '\\`')}\``
}

function renderInlineElementTag(value: string): string {
  return mdInlineCode(value)
}

function renderMarkdownText(value: string): string {
  return value
    .split(/(`[^`]*`)/g)
    .map((segment, index) => {
      if (index % 2 === 1) return segment

      return segment.replace(/<\/?[a-z][a-z0-9-]*>/gi, renderInlineElementTag)
    })
    .join('')
}

function mdCodeBlock(language: string, code: string): string {
  return [`\`\`\`${language}`, code, '```'].join('\n')
}

function renderStringList(items: string[]): string {
  if (items.length === 0) return '- None.'
  return items.map(item => `- ${renderMarkdownText(item)}`).join('\n')
}

function renderCodeList(items: string[]): string {
  if (items.length === 0) return '- None.'
  return items.map(item => `- ${mdInlineCode(item)}`).join('\n')
}

function renderPropsTable(component: ZeusWebAiComponent): string {
  if (component.props.length === 0) return 'No public props documented.'

  return [
    '| Prop | Type | Default | Description |',
    '| --- | --- | --- | --- |',
    ...component.props.map(prop => {
      const type = mdInlineCode(prop.type)
      const values = prop.values?.length
        ? `<br />Values: ${prop.values.map(mdInlineCode).join(', ')}`
        : ''
      const defaultValue = prop.default ? mdInlineCode(prop.default) : '-'

      return `| ${mdInlineCode(prop.name)} | ${type}${values} | ${defaultValue} | ${prop.description} |`
    }),
  ].join('\n')
}

function renderEventsTable(component: ZeusWebAiComponent): string {
  if (component.events.length === 0) return 'No public events documented.'

  return [
    '| Event | React prop | Detail | Description |',
    '| --- | --- | --- | --- |',
    ...component.events.map(event => {
      const detail = Object.entries(event.detail)
        .map(([key, value]) => `${key}: ${value}`)
        .join(', ')

      return `| ${mdInlineCode(event.name)} | ${mdInlineCode(event.reactName)} | ${mdInlineCode(detail)} | ${event.description} |`
    }),
  ].join('\n')
}

function renderSlotsTable(component: ZeusWebAiComponent): string {
  if (component.slots.length === 0) return 'No slots documented.'

  return [
    '| Slot | Description |',
    '| --- | --- |',
    ...component.slots.map(slot => {
      return `| ${mdInlineCode(slot.name)} | ${slot.description} |`
    }),
  ].join('\n')
}

function renderExamples(component: ZeusWebAiComponent): string {
  if (component.examples.length === 0) return 'No examples documented.'

  return component.examples
    .map(example => {
      return [
        `### ${example.title}`,
        '',
        mdCodeBlock('tsx', example.code),
      ].join('\n')
    })
    .join('\n\n')
}

function renderRegistryStatus(
  component: ZeusWebAiComponent,
  registryItem?: RegistryItem,
): string {
  if (!registryItem) {
    return [
      '## Registry',
      '',
      'Registry source: not available yet.',
      '',
      `The ${mdInlineCode(component.name)} primitive is available through ${mdInlineCode(component.primitivePackage)}, but it is not currently installable through ${mdInlineCode(`zweb add ${component.name}`)}.`,
      '',
      'Use the primitive package directly until a registry template is added.',
    ].join('\n')
  }

  return [
    '## Registry',
    '',
    'Registry source: available.',
    '',
    `Add command: ${mdInlineCode(component.registryCommand)}`,
    '',
    `Type: ${mdInlineCode(registryItem.type)}`,
    '',
    'Dependencies:',
    '',
    renderCodeList(registryItem.dependencies ?? []),
    '',
    'Registry dependencies:',
    '',
    renderCodeList(registryItem.registryDependencies ?? []),
    '',
    'Files:',
    '',
    registryItem.files.length === 0
      ? '- None.'
      : registryItem.files
          .map(file => {
            return `- ${mdInlineCode(file.source)} → ${mdInlineCode(file.target)}`
          })
          .join('\n'),
  ].join('\n')
}

function renderAddSection(
  component: ZeusWebAiComponent,
  registryItem?: RegistryItem,
): string {
  if (!registryItem) {
    return [
      '## Install',
      '',
      'This component does not have a registry template yet.',
      '',
      'Install the primitive package instead:',
      '',
      mdCodeBlock('bash', `pnpm add ${component.primitivePackage}`),
    ].join('\n')
  }

  return ['## Add', '', mdCodeBlock('bash', component.registryCommand)].join(
    '\n',
  )
}

function renderImportsSection(
  component: ZeusWebAiComponent,
  registryItem?: RegistryItem,
): string {
  const lines = ['## Imports', '']

  if (registryItem) {
    lines.push(
      'Styled registry component:',
      '',
      mdCodeBlock('tsx', component.styledImport),
      '',
    )
  } else {
    lines.push('Styled registry component:', '', 'Not available yet.', '')
  }

  lines.push(
    'Primitive React wrapper:',
    '',
    mdCodeBlock('tsx', component.reactImport),
    '',
    'Web Component entry:',
    '',
    mdCodeBlock('ts', component.webComponentImport),
  )

  return lines.join('\n')
}

export function renderComponentDoc(
  component: ZeusWebAiComponent,
  registryItem?: RegistryItem,
  root = process.cwd(),
): string {
  const catalogItem = getCatalogItem(component.name)

  return [
    renderPageFrontmatter(catalogItem),
    '',
    generatedHeader,
    '',
    `# ${catalogItem.title}`,
    '',
    component.description,
    '',
    renderCatalogBadges(catalogItem, [
      registryItem ? component.registryCommand : 'primitive-only',
      'Generated',
    ]),
    '',
    renderCatalogPlayground(catalogItem, root),
    '',
    renderAddSection(component, registryItem),
    '',
    renderImportsSection(component, registryItem),
    '',
    '## Props',
    '',
    renderPropsTable(component),
    '',
    '## Events',
    '',
    renderEventsTable(component),
    '',
    '## Slots',
    '',
    renderSlotsTable(component),
    '',
    '## Styling',
    '',
    `Uses Tailwind: ${component.styling.usesTailwind ? 'yes' : 'no'}`,
    '',
    'Theme tokens:',
    '',
    renderCodeList(component.styling.themeTokens),
    '',
    'Internal selectors:',
    '',
    renderCodeList(component.styling.internalSelectors),
    '',
    renderRegistryStatus(component, registryItem),
    '',
    '## AI usage rules',
    '',
    'Do:',
    '',
    renderStringList(component.aiRules.do),
    '',
    'Do not:',
    '',
    renderStringList(component.aiRules.dont),
    '',
    '## Examples',
    '',
    renderExamples(component),
    '',
  ].join('\n')
}

function renderAdvancedMembers(
  title: string,
  members: Record<string, string[]> | undefined,
): string {
  const entries = Object.entries(members || {})

  if (entries.length === 0) {
    return [`## ${title}`, '', 'No public members documented.'].join('\n')
  }

  return [
    `## ${title}`,
    '',
    ...entries.flatMap(([tagName, names]) => [
      `### ${mdInlineCode(tagName)}`,
      '',
      renderCodeList(names),
      '',
    ]),
  ].join('\n')
}

function getAdvancedExampleLanguage(title: string): string {
  if (title.includes('React')) return 'tsx'
  if (title.includes('Web Component')) return 'html'
  return 'ts'
}

function renderAdvancedExamples(
  examples: ZeusWebAiAdvancedComponent['examples'],
): string {
  if (examples.length === 0) {
    return ['## Examples', '', 'No usage examples documented.'].join('\n')
  }

  return [
    '## Examples',
    '',
    ...examples.flatMap(example => [
      `### ${example.title}`,
      '',
      renderMarkdownText(example.description),
      '',
      mdCodeBlock(getAdvancedExampleLanguage(example.title), example.code),
      '',
    ]),
  ].join('\n')
}

export function renderAdvancedComponentDoc(
  component: ComponentCatalogItem,
  metadata?: ZeusWebAiAdvancedComponent,
  root = process.cwd(),
): string {
  return [
    renderPageFrontmatter(component),
    '',
    generatedHeader,
    '',
    `# ${component.title}`,
    '',
    renderMarkdownText(metadata ? metadata.summary : component.description),
    '',
    renderCatalogBadges(component, ['Generated']),
    '',
    renderCatalogPlayground(component, root),
    '',
    '## When to use',
    '',
    renderStringList(metadata ? metadata.whenToUse : []),
    '',
    '## When not to use',
    '',
    renderStringList(metadata ? metadata.doNotUseFor : []),
    '',
    '## Install',
    '',
    mdCodeBlock('bash', `pnpm add ${component.packageName}`),
    '',
    '## Component family',
    '',
    renderCodeList(metadata ? metadata.components : []),
    '',
    renderAdvancedMembers('Slots', metadata ? metadata.slots : undefined),
    '',
    renderAdvancedMembers('Events', metadata ? metadata.events : undefined),
    '',
    renderAdvancedMembers('Methods', metadata ? metadata.methods : undefined),
    '',
    renderAdvancedExamples(metadata ? metadata.examples : []),
    '',
    '## AI usage hints',
    '',
    renderStringList(metadata ? metadata.promptHints : []),
    '',
  ].join('\n')
}

export function renderComponentsIndex(context: ComponentDocsContext): string {
  return [
    generatedHeader,
    '',
    '# Components',
    '',
    `Browse all ${componentCatalog.length} public component packages by capability. Each component has one canonical page with a live preview, framework-specific source, installation guidance and API details.`,
    '',
    '<ComponentDirectory />',
    '',
    '## Recommended workflow',
    '',
    renderStringList(context.metadata.recommendedWorkflow),
    '',
    '## Current registry components',
    '',
    renderCodeList(
      context.metadata.components
        .filter(component => isRegistryComponent(context.registry, component))
        .map(component => component.name),
    ),
    '',
    'Registry availability applies to copyable primitive source. Advanced components are installed from their package.',
    '',
  ].join('\n')
}

export function generateComponentDocs(
  context = createComponentDocsContext(),
  root = process.cwd(),
): GeneratedDoc[] {
  const docs: GeneratedDoc[] = [
    {
      path: 'apps/docs/components/index.md',
      content: renderComponentsIndex(context),
    },
  ]
  const primitiveByName = new Map(
    context.metadata.components.map(component => [component.name, component]),
  )
  const advancedByName = new Map(
    context.metadata.advancedComponents.map(component => [
      component.name,
      component,
    ]),
  )

  for (const catalogItem of componentCatalog) {
    if (catalogItem.packageGroup === 'primitives') {
      const primitive = primitiveByName.get(catalogItem.name)

      if (!primitive) {
        throw new Error(
          `Missing primitive AI metadata for ${catalogItem.packageName}.`,
        )
      }

      const registryItem = findRegistryItem(context.registry, primitive)

      docs.push({
        path: `apps/docs/components/${catalogItem.name}.md`,
        content: renderComponentDoc(primitive, registryItem, root),
      })
      continue
    }

    const advanced = advancedByName.get(catalogItem.name)

    if (!advanced) {
      throw new Error(
        `Missing advanced AI metadata for ${catalogItem.packageName}.`,
      )
    }

    docs.push({
      path: `apps/docs/components/${catalogItem.name}.md`,
      content: renderAdvancedComponentDoc(catalogItem, advanced, root),
    })
  }

  return docs
}
