import type {
  PlaygroundComponent,
  PlaygroundComponentName,
} from '../../apps/docs/.vitepress/data/playground-manifest'
import type {
  PlaygroundFramework,
  PlaygroundSource,
  PlaygroundSourceSet,
} from '../../apps/docs/.vitepress/data/playground-sources'
import type { GeneratedDoc } from './component-docs'

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { playgroundComponents } from '../../apps/docs/.vitepress/data/playground-manifest'
import { playgroundSources } from '../../apps/docs/.vitepress/data/playground-sources'

interface FrameworkContract {
  exportPath: string
  sourceKey: PlaygroundFramework
}

interface PackageManifest {
  exports: Record<string, unknown>
}

const generatedHeader =
  '<!-- This file is generated by scripts/commands/generate-docs.ts. Do not edit manually. -->'

const frameworkContracts: FrameworkContract[] = [
  {
    exportPath: './wc/auto',
    sourceKey: 'webComponent',
  },
  {
    exportPath: './react',
    sourceKey: 'react',
  },
  {
    exportPath: './vue',
    sourceKey: 'vue',
  },
]

function readPackageManifest(
  component: PlaygroundComponent,
  root = process.cwd(),
): PackageManifest {
  const path = resolve(
    root,
    'packages',
    component.group,
    component.name,
    'package.json',
  )

  return JSON.parse(readFileSync(path, 'utf-8')) as PackageManifest
}

export function getSupportedPlaygroundFrameworks(
  component: PlaygroundComponent,
  root = process.cwd(),
): PlaygroundFramework[] {
  const manifest = readPackageManifest(component, root)

  return frameworkContracts
    .filter(contract => contract.exportPath in manifest.exports)
    .map(contract => contract.sourceKey)
}

function validateSource(
  component: PlaygroundComponent,
  framework: PlaygroundFramework,
  source: PlaygroundSource | undefined,
): PlaygroundSource {
  if (!source) {
    throw new Error(
      `${component.packageName} exports ${framework}, but its Playground source is missing.`,
    )
  }

  const expectedImport =
    framework === 'webComponent'
      ? `${component.packageName}/wc/auto`
      : `${component.packageName}/${framework}`

  if (!source.code.includes(expectedImport)) {
    throw new Error(
      `${component.packageName} ${framework} source must import ${expectedImport}.`,
    )
  }

  return source
}

function validateSourceSet(
  component: PlaygroundComponent,
  sources: PlaygroundSourceSet,
  root = process.cwd(),
): PlaygroundFramework[] {
  const supported = getSupportedPlaygroundFrameworks(component, root)
  const sourceKeys = frameworkContracts
    .map(contract => contract.sourceKey)
    .filter(key => Boolean(sources[key]))

  if (
    supported.length !== sourceKeys.length ||
    supported.some(framework => !sourceKeys.includes(framework))
  ) {
    throw new Error(
      `${component.packageName} Playground sources do not match its package exports.`,
    )
  }

  return supported
}

function renderSource(source: PlaygroundSource): string {
  return [
    `\`\`\`${source.language} [${source.label}]`,
    source.code,
    '```',
  ].join('\n')
}

function renderSourceCodeGroup(
  component: PlaygroundComponent,
  sources: PlaygroundSourceSet,
  root = process.cwd(),
): string {
  const supported = validateSourceSet(component, sources, root)

  return [
    '::: code-group',
    ...supported.map(framework => {
      return renderSource(
        validateSource(component, framework, sources[framework]),
      )
    }),
    ':::',
  ].join('\n\n')
}

function renderPlaygroundComponent(component: PlaygroundComponent): string {
  if (component.name === 'data-grid') {
    return '<DataGridPlayground />'
  }

  return `<ComponentPlayground name="${component.name}" />`
}

export function renderPlaygroundDoc(
  component: PlaygroundComponent,
  sources: PlaygroundSourceSet,
  root = process.cwd(),
): string {
  const pageClass =
    component.name === 'data-grid'
      ? 'component-playground-page data-grid-playground-page'
      : 'component-playground-page'
  const performanceDescription =
    component.name === 'data-grid'
      ? [
          '',
          'Explore two-axis virtualization across datasets with up to 100,000 rows and',
          '1,000 columns.',
        ]
      : []

  return [
    '---',
    'aside: false',
    `pageClass: ${pageClass}`,
    '---',
    '',
    generatedHeader,
    '',
    `# ${component.title} Playground`,
    '',
    component.description,
    ...performanceDescription,
    '',
    '<ClientOnly>',
    renderPlaygroundComponent(component),
    '</ClientOnly>',
    '',
    '## Source',
    '',
    'Choose the framework entry that matches your application.',
    '',
    renderSourceCodeGroup(component, sources, root),
    '',
  ].join('\n')
}

export function generatePlaygroundDocs(root = process.cwd()): GeneratedDoc[] {
  return playgroundComponents.map(component => {
    const sources = playgroundSources[component.name as PlaygroundComponentName]

    return {
      path: `apps/docs/playground/${component.name}/index.md`,
      content: renderPlaygroundDoc(component, sources, root),
    }
  })
}
