import type { ShowcaseComponent } from './types'

const baseSections = [
  'basic',
  'states',
  'theme',
  'accessibility',
  'production',
] as const

const formSections = [
  'basic',
  'states',
  'controlled',
  'uncontrolled',
  'events',
  'theme',
  'accessibility',
  'production',
] as const

export const showcaseComponents: ShowcaseComponent[] = [
  {
    name: 'button',
    title: 'Button',
    routePath: '/components/button',
    packageName: '@zeus-web/button',
    group: 'Actions',
    description:
      'Action component for commands, form submission, toolbar controls and icon buttons.',
    registryCommand: 'zweb add button',
    imports: {
      react: "import { Button } from '@/components/ui/button'",
      vue: "import { Button } from '@zeus-web/button/vue'",
      webComponent: "import '@zeus-web/button/wc'",
      registry: 'zweb add button',
    },
    sections: [
      'basic',
      'variants',
      'sizes',
      'states',
      'events',
      'icons',
      'theme',
      'accessibility',
      'production',
    ],
    states: [
      'default',
      'primary',
      'secondary',
      'outline',
      'ghost',
      'danger',
      'disabled',
      'loading',
      'icon-only',
    ],
    events: [
      {
        name: 'press',
        reactName: 'onPress',
        vueName: 'press',
        description: 'Emitted when the button is activated and not disabled.',
      },
    ],
    themeTokens: [
      'primary',
      'primary-foreground',
      'ring',
      'border',
      'destructive',
    ],
    iconExamples: ['check', 'plus', 'trash', 'loader'],
    productionPatterns: [
      'Form actions',
      'Toolbar action',
      'Destructive confirmation',
      'Icon-only button',
    ],
  },
  {
    name: 'input',
    title: 'Input',
    routePath: '/components/input',
    packageName: '@zeus-web/input',
    group: 'Forms',
    description: 'Single-line text input for forms, filters and search fields.',
    registryCommand: 'zweb add input',
    imports: {
      react: "import { Input } from '@/components/ui/input'",
      vue: "import { Input } from '@zeus-web/input/vue'",
      webComponent: "import '@zeus-web/input/wc'",
      registry: 'zweb add input',
    },
    sections: [...formSections, 'icons'],
    states: [
      'default',
      'disabled',
      'readonly',
      'invalid',
      'with-prefix',
      'with-suffix',
    ],
    events: [
      {
        name: 'value-change',
        reactName: 'onValueChange',
        vueName: 'value-change',
        description: 'Emitted when the input value changes.',
      },
      {
        name: 'focus-change',
        reactName: 'onFocusChange',
        vueName: 'focus-change',
        description: 'Emitted when focus state changes.',
      },
    ],
    themeTokens: ['input', 'ring', 'muted-foreground', 'destructive'],
    iconExamples: ['search', 'eye', 'eye-off'],
    productionPatterns: ['Search input', 'Login field', 'Settings field'],
  },
  {
    name: 'checkbox',
    title: 'Checkbox',
    routePath: '/components/checkbox',
    packageName: '@zeus-web/checkbox',
    group: 'Forms',
    description:
      'Boolean choice control with checked and indeterminate states.',
    registryCommand: 'zweb add checkbox',
    imports: {
      react: "import { Checkbox } from '@/components/ui/checkbox'",
      vue: "import { Checkbox } from '@zeus-web/checkbox/vue'",
      webComponent: "import '@zeus-web/checkbox/wc'",
      registry: 'zweb add checkbox',
    },
    sections: formSections,
    states: ['unchecked', 'checked', 'indeterminate', 'disabled', 'required'],
    events: [
      {
        name: 'checked-change',
        reactName: 'onCheckedChange',
        vueName: 'checked-change',
        description: 'Emitted when checked state changes.',
      },
    ],
    themeTokens: ['primary', 'primary-foreground', 'ring'],
    iconExamples: ['check', 'minus'],
    productionPatterns: [
      'Terms checkbox',
      'Bulk selection',
      'Indeterminate table selection',
    ],
  },
  {
    name: 'switch',
    title: 'Switch',
    routePath: '/components/switch',
    packageName: '@zeus-web/switch',
    group: 'Forms',
    description: 'On/off setting control.',
    registryCommand: 'zweb add switch',
    imports: {
      react: "import { Switch } from '@/components/ui/switch'",
      vue: "import { Switch } from '@zeus-web/switch/vue'",
      webComponent: "import '@zeus-web/switch/wc'",
      registry: 'zweb add switch',
    },
    sections: formSections,
    states: ['off', 'on', 'disabled', 'required'],
    events: [
      {
        name: 'checked-change',
        reactName: 'onCheckedChange',
        vueName: 'checked-change',
        description: 'Emitted when checked state changes.',
      },
    ],
    themeTokens: ['primary', 'input', 'ring'],
    iconExamples: ['sun', 'moon'],
    productionPatterns: [
      'Notification settings',
      'Feature flag toggle',
      'Theme preference',
    ],
  },
  {
    name: 'tabs',
    title: 'Tabs',
    routePath: '/components/tabs',
    packageName: '@zeus-web/tabs',
    group: 'Navigation',
    description: 'Tabbed navigation with triggers and content panels.',
    registryCommand: 'zweb add tabs',
    imports: {
      react:
        "import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'",
      vue: "import { Tabs, TabsList, TabsTrigger, TabsContent } from '@zeus-web/tabs/vue'",
      webComponent: "import '@zeus-web/tabs/wc'",
      registry: 'zweb add tabs',
    },
    sections: [
      'basic',
      'variants',
      'states',
      'controlled',
      'uncontrolled',
      'events',
      'theme',
      'accessibility',
      'production',
    ],
    states: ['horizontal', 'vertical', 'disabled-trigger', 'controlled'],
    events: [
      {
        name: 'value-change',
        reactName: 'onValueChange',
        vueName: 'value-change',
        description: 'Emitted when active tab changes.',
      },
    ],
    themeTokens: ['muted', 'muted-foreground', 'ring'],
    iconExamples: ['settings', 'user'],
    productionPatterns: [
      'Settings page',
      'Dashboard panels',
      'Profile details',
    ],
  },
  {
    name: 'dialog',
    title: 'Dialog',
    routePath: '/components/dialog',
    packageName: '@zeus-web/dialog',
    group: 'Feedback',
    description: 'Modal dialog for focused tasks and confirmations.',
    registryCommand: 'zweb add dialog',
    imports: {
      react:
        "import { Dialog, DialogTrigger, DialogContent, DialogTitle } from '@/components/ui/dialog'",
      vue: "import { Dialog, DialogTrigger, DialogContent, DialogTitle } from '@zeus-web/dialog/vue'",
      webComponent: "import '@zeus-web/dialog/wc'",
      registry: 'zweb add dialog',
    },
    sections: [
      'basic',
      'states',
      'controlled',
      'uncontrolled',
      'events',
      'theme',
      'accessibility',
      'production',
    ],
    states: ['closed', 'open', 'modal', 'non-modal'],
    events: [
      {
        name: 'open-change',
        reactName: 'onOpenChange',
        vueName: 'open-change',
        description: 'Emitted when open state changes.',
      },
    ],
    themeTokens: ['background', 'foreground', 'ring', 'border'],
    iconExamples: ['x', 'alert-triangle'],
    productionPatterns: [
      'Create project dialog',
      'Confirmation dialog',
      'Edit settings modal',
    ],
  },
  {
    name: 'label',
    title: 'Label',
    routePath: '/components/label',
    packageName: '@zeus-web/label',
    group: 'Forms',
    description: 'Accessible form label with required and disabled states.',
    registryCommand: 'zweb add label',
    imports: {
      react: "import { Label } from '@/components/ui/label'",
      vue: "import { Label } from '@zeus-web/label/vue'",
      webComponent: "import '@zeus-web/label/wc'",
      registry: 'zweb add label',
    },
    sections: baseSections,
    states: ['default', 'required', 'disabled', 'visually-hidden'],
    events: [],
    themeTokens: ['foreground', 'destructive', 'muted-foreground'],
    iconExamples: ['info'],
    productionPatterns: [
      'Form label',
      'Required field label',
      'Accessible hidden label',
    ],
  },
  {
    name: 'textarea',
    title: 'Textarea',
    routePath: '/components/textarea',
    packageName: '@zeus-web/textarea',
    group: 'Forms',
    description:
      'Multi-line text input with validation and help message support.',
    registryCommand: 'zweb add textarea',
    imports: {
      react: "import { Textarea } from '@/components/ui/textarea'",
      vue: "import { Textarea } from '@zeus-web/textarea/vue'",
      webComponent: "import '@zeus-web/textarea/wc'",
      registry: 'zweb add textarea',
    },
    sections: formSections,
    states: ['default', 'disabled', 'invalid', 'with-message'],
    events: [
      {
        name: 'value-change',
        reactName: 'onValueChange',
        vueName: 'value-change',
        description: 'Emitted when value changes.',
      },
    ],
    themeTokens: ['input', 'ring', 'muted-foreground', 'destructive'],
    iconExamples: ['info'],
    productionPatterns: ['Feedback form', 'Deployment note', 'Support message'],
  },
  {
    name: 'radio-group',
    title: 'Radio Group',
    routePath: '/components/radio-group',
    packageName: '@zeus-web/radio-group',
    group: 'Forms',
    description: 'Single-selection control group.',
    registryCommand: 'zweb add radio-group',
    imports: {
      react:
        "import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'",
      vue: "import { RadioGroup, RadioGroupItem } from '@zeus-web/radio-group/vue'",
      webComponent: "import '@zeus-web/radio-group/wc'",
      registry: 'zweb add radio-group',
    },
    sections: formSections,
    states: ['vertical', 'horizontal', 'disabled', 'required'],
    events: [
      {
        name: 'value-change',
        reactName: 'onValueChange',
        vueName: 'value-change',
        description: 'Emitted when selected value changes.',
      },
    ],
    themeTokens: ['primary', 'ring', 'muted-foreground'],
    iconExamples: ['circle-check'],
    productionPatterns: [
      'Plan selection',
      'Notification frequency',
      'Environment selection',
    ],
  },
  {
    name: 'select',
    title: 'Select',
    routePath: '/components/select',
    packageName: '@zeus-web/select',
    group: 'Forms',
    description: 'Native select primitive styled with Zeus Web tokens.',
    registryCommand: 'zweb add select',
    imports: {
      react: "import { Select } from '@/components/ui/select'",
      vue: "import { Select } from '@zeus-web/select/vue'",
      webComponent: "import '@zeus-web/select/wc'",
      registry: 'zweb add select',
    },
    sections: formSections,
    states: ['default', 'disabled', 'invalid'],
    events: [
      {
        name: 'value-change',
        reactName: 'onValueChange',
        vueName: 'value-change',
        description: 'Emitted when selected value changes.',
      },
    ],
    themeTokens: ['input', 'ring', 'background', 'foreground'],
    iconExamples: ['chevron-down'],
    productionPatterns: ['Environment select', 'Role select', 'Status filter'],
  },
  {
    name: 'card',
    title: 'Card',
    routePath: '/components/card',
    packageName: '@zeus-web/card',
    group: 'Layout',
    description: 'Surface container for grouped content.',
    registryCommand: 'zweb add card',
    imports: {
      react:
        "import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'",
      vue: "import { Card, CardHeader, CardTitle, CardContent } from '@zeus-web/card/vue'",
      webComponent: "import '@zeus-web/card/wc'",
      registry: 'zweb add card',
    },
    sections: baseSections,
    states: ['default', 'interactive', 'muted'],
    events: [],
    themeTokens: ['card', 'card-foreground', 'border'],
    iconExamples: ['info', 'settings'],
    productionPatterns: ['Dashboard metric', 'Settings panel', 'Profile card'],
  },
  {
    name: 'badge',
    title: 'Badge',
    routePath: '/components/badge',
    packageName: '@zeus-web/badge',
    group: 'Feedback',
    description: 'Small status label.',
    registryCommand: 'zweb add badge',
    imports: {
      react: "import { Badge } from '@/components/ui/badge'",
      vue: "import { Badge } from '@zeus-web/badge/vue'",
      webComponent: "import '@zeus-web/badge/wc'",
      registry: 'zweb add badge',
    },
    sections: [
      'basic',
      'variants',
      'states',
      'icons',
      'theme',
      'accessibility',
      'production',
    ],
    states: ['default', 'secondary', 'outline', 'danger'],
    events: [],
    themeTokens: ['primary', 'secondary', 'destructive', 'border'],
    iconExamples: ['check', 'x', 'alert-triangle'],
    productionPatterns: ['Status badge', 'Plan badge', 'Environment label'],
  },
  {
    name: 'separator',
    title: 'Separator',
    routePath: '/components/separator',
    packageName: '@zeus-web/separator',
    group: 'Layout',
    description: 'Visual or semantic content separator.',
    registryCommand: 'zweb add separator',
    imports: {
      react: "import { Separator } from '@/components/ui/separator'",
      vue: "import { Separator } from '@zeus-web/separator/vue'",
      webComponent: "import '@zeus-web/separator/wc'",
      registry: 'zweb add separator',
    },
    sections: baseSections,
    states: ['horizontal', 'vertical', 'decorative'],
    events: [],
    themeTokens: ['border'],
    iconExamples: [],
    productionPatterns: [
      'Settings group divider',
      'Toolbar divider',
      'Sidebar separator',
    ],
  },
  {
    name: 'skeleton',
    title: 'Skeleton',
    routePath: '/components/skeleton',
    packageName: '@zeus-web/skeleton',
    group: 'Feedback',
    description: 'Loading placeholder for content.',
    registryCommand: 'zweb add skeleton',
    imports: {
      react: "import { Skeleton } from '@/components/ui/skeleton'",
      vue: "import { Skeleton } from '@zeus-web/skeleton/vue'",
      webComponent: "import '@zeus-web/skeleton/wc'",
      registry: 'zweb add skeleton',
    },
    sections: [
      'basic',
      'variants',
      'states',
      'theme',
      'accessibility',
      'production',
    ],
    states: ['text', 'avatar', 'card', 'table'],
    events: [],
    themeTokens: ['muted'],
    iconExamples: [],
    productionPatterns: [
      'Loading card',
      'Loading table row',
      'Loading profile',
    ],
  },
  {
    name: 'alert',
    title: 'Alert',
    routePath: '/components/alert',
    packageName: '@zeus-web/alert',
    group: 'Feedback',
    description: 'Inline contextual feedback.',
    registryCommand: 'zweb add alert',
    imports: {
      react:
        "import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert'",
      vue: "import { Alert, AlertTitle, AlertDescription } from '@zeus-web/alert/vue'",
      webComponent: "import '@zeus-web/alert/wc'",
      registry: 'zweb add alert',
    },
    sections: [
      'basic',
      'variants',
      'states',
      'icons',
      'theme',
      'accessibility',
      'production',
    ],
    states: ['info', 'success', 'warning', 'danger'],
    events: [],
    themeTokens: ['background', 'foreground', 'destructive', 'border'],
    iconExamples: ['info', 'circle-check', 'alert-triangle', 'circle-x'],
    productionPatterns: ['Form error', 'System notice', 'Deployment warning'],
  },
  {
    name: 'collapsible',
    title: 'Collapsible',
    routePath: '/components/collapsible',
    packageName: '@zeus-web/collapsible',
    group: 'Disclosure',
    description: 'Expandable content region.',
    registryCommand: 'zweb add collapsible',
    imports: {
      react:
        "import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@/components/ui/collapsible'",
      vue: "import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@zeus-web/collapsible/vue'",
      webComponent: "import '@zeus-web/collapsible/wc'",
      registry: 'zweb add collapsible',
    },
    sections: [
      'basic',
      'states',
      'controlled',
      'uncontrolled',
      'events',
      'theme',
      'accessibility',
      'production',
    ],
    states: ['closed', 'open', 'disabled'],
    events: [
      {
        name: 'open-change',
        reactName: 'onOpenChange',
        vueName: 'open-change',
        description: 'Emitted when open state changes.',
      },
    ],
    themeTokens: ['border', 'muted'],
    iconExamples: ['chevron-down', 'chevron-up'],
    productionPatterns: [
      'Advanced settings',
      'Expandable log details',
      'FAQ item',
    ],
  },
  {
    name: 'accordion',
    title: 'Accordion',
    routePath: '/components/accordion',
    packageName: '@zeus-web/accordion',
    group: 'Disclosure',
    description: 'Stacked expandable sections.',
    registryCommand: 'zweb add accordion',
    imports: {
      react:
        "import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion'",
      vue: "import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@zeus-web/accordion/vue'",
      webComponent: "import '@zeus-web/accordion/wc'",
      registry: 'zweb add accordion',
    },
    sections: [
      'basic',
      'states',
      'controlled',
      'uncontrolled',
      'events',
      'theme',
      'accessibility',
      'production',
    ],
    states: ['single', 'multiple', 'collapsible', 'disabled'],
    events: [
      {
        name: 'value-change',
        reactName: 'onValueChange',
        vueName: 'value-change',
        description: 'Emitted when selected item changes.',
      },
    ],
    themeTokens: ['border', 'muted', 'ring'],
    iconExamples: ['chevron-down', 'chevron-up'],
    productionPatterns: [
      'FAQ',
      'Settings sections',
      'Documentation navigation',
    ],
  },
  {
    name: 'tooltip',
    title: 'Tooltip',
    routePath: '/components/tooltip',
    packageName: '@zeus-web/tooltip',
    group: 'Feedback',
    description: 'Small contextual help on hover or focus.',
    registryCommand: 'zweb add tooltip',
    imports: {
      react:
        "import { Tooltip, TooltipTrigger, TooltipContent } from '@/components/ui/tooltip'",
      vue: "import { Tooltip, TooltipTrigger, TooltipContent } from '@zeus-web/tooltip/vue'",
      webComponent: "import '@zeus-web/tooltip/wc'",
      registry: 'zweb add tooltip',
    },
    sections: [
      'basic',
      'states',
      'controlled',
      'uncontrolled',
      'theme',
      'accessibility',
      'production',
    ],
    states: ['closed', 'open', 'delay', 'disabled'],
    events: [],
    themeTokens: ['popover', 'popover-foreground', 'ring'],
    iconExamples: ['info', 'help-circle'],
    productionPatterns: ['Icon help', 'Truncated text help', 'Form hint'],
  },
  {
    name: 'progress',
    title: 'Progress',
    routePath: '/components/progress',
    packageName: '@zeus-web/progress',
    group: 'Feedback',
    description: 'Progress indicator for known completion values.',
    registryCommand: 'zweb add progress',
    imports: {
      react: "import { Progress } from '@/components/ui/progress'",
      vue: "import { Progress } from '@zeus-web/progress/vue'",
      webComponent: "import '@zeus-web/progress/wc'",
      registry: 'zweb add progress',
    },
    sections: [
      'basic',
      'variants',
      'states',
      'theme',
      'accessibility',
      'production',
    ],
    states: ['0', '25', '50', '75', '100', 'indeterminate'],
    events: [],
    themeTokens: ['primary', 'muted'],
    iconExamples: ['loader'],
    productionPatterns: [
      'Upload progress',
      'Deployment progress',
      'Profile completion',
    ],
  },
  {
    name: 'avatar',
    title: 'Avatar',
    routePath: '/components/avatar',
    packageName: '@zeus-web/avatar',
    group: 'Media',
    description: 'User image with fallback state.',
    registryCommand: 'zweb add avatar',
    imports: {
      react:
        "import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar'",
      vue: "import { Avatar, AvatarImage, AvatarFallback } from '@zeus-web/avatar/vue'",
      webComponent: "import '@zeus-web/avatar/wc'",
      registry: 'zweb add avatar',
    },
    sections: [
      'basic',
      'variants',
      'states',
      'theme',
      'accessibility',
      'production',
    ],
    states: ['image', 'fallback', 'group', 'loading-error'],
    events: [],
    themeTokens: ['muted', 'muted-foreground'],
    iconExamples: ['user'],
    productionPatterns: ['User profile', 'Assignee list', 'Team member card'],
  },
]

export const deferredComponents = ['popover', 'dropdown', 'toast'] as const
