import { Select as SelectPrimitive } from '@zeus-web/select/react'
import * as React from 'react'

import { cn } from '@/lib/utils'

export interface SelectProps extends React.ComponentPropsWithoutRef<
  typeof SelectPrimitive
> {}

export const Select = React.forwardRef<HTMLElement, SelectProps>(
  ({ className, ...props }, ref) => {
    return (
      <SelectPrimitive
        ref={ref}
        className={cn(
          [
            'block w-full min-w-0 text-sm text-foreground',
            '[&_[data-slot=select-control]]:relative',
            '[&_[data-slot=select-control]]:min-w-0',
            '[&_[data-slot=select-native]]:sr-only',
            '[&_[data-slot=select-native]]:pointer-events-none',
            '[&_[data-slot=select-trigger]]:flex',
            '[&_[data-slot=select-trigger]]:h-9',
            '[&_[data-slot=select-trigger]]:w-full',
            '[&_[data-slot=select-trigger]]:min-w-0',
            '[&_[data-slot=select-trigger]]:items-center',
            '[&_[data-slot=select-trigger]]:justify-between',
            '[&_[data-slot=select-trigger]]:gap-2',
            '[&_[data-slot=select-trigger]]:rounded-md',
            '[&_[data-slot=select-trigger]]:border',
            '[&_[data-slot=select-trigger]]:border-input',
            '[&_[data-slot=select-trigger]]:bg-background',
            '[&_[data-slot=select-trigger]]:px-3',
            '[&_[data-slot=select-trigger]]:py-2',
            '[&_[data-slot=select-trigger]]:text-left',
            '[&_[data-slot=select-trigger]]:text-sm',
            '[&_[data-slot=select-trigger]]:shadow-sm',
            '[&_[data-slot=select-trigger]]:outline-none',
            '[&_[data-slot=select-trigger]]:transition-colors',
            '[&_[data-slot=select-trigger]]:hover:border-foreground/30',
            '[&_[data-slot=select-trigger]]:focus-visible:ring-1',
            '[&_[data-slot=select-trigger]]:focus-visible:ring-ring',
            '[&_[data-slot=select-value]]:min-w-0',
            '[&_[data-slot=select-value]]:flex-1',
            '[&_[data-slot=select-value]]:truncate',
            '[&_[data-slot=select-value][data-placeholder]]:text-muted-foreground',
            '[&_[data-slot=select-indicator]]:size-2',
            '[&_[data-slot=select-indicator]]:shrink-0',
            '[&_[data-slot=select-indicator]]:border-b-2',
            '[&_[data-slot=select-indicator]]:border-r-2',
            '[&_[data-slot=select-indicator]]:border-current',
            '[&_[data-slot=select-indicator]]:transition-transform',
            '[&_[data-slot=select-indicator]]:[transform:translateY(-2px)_rotate(45deg)]',
            '[&_[data-slot=select-content]]:absolute',
            '[&_[data-slot=select-content]]:left-0',
            '[&_[data-slot=select-content]]:right-0',
            '[&_[data-slot=select-content]]:top-[calc(100%+0.25rem)]',
            '[&_[data-slot=select-content]]:z-50',
            '[&_[data-slot=select-content]]:max-h-[min(16rem,var(--zw-select-available-height,calc(100vh-1rem)))]',
            '[&_[data-slot=select-content]]:overflow-y-auto',
            '[&_[data-slot=select-content]]:overscroll-contain',
            '[&_[data-slot=select-content]]:rounded-md',
            '[&_[data-slot=select-content]]:border',
            '[&_[data-slot=select-content]]:border-border',
            '[&_[data-slot=select-content]]:bg-popover',
            '[&_[data-slot=select-content]]:p-1',
            '[&_[data-slot=select-content]]:text-popover-foreground',
            '[&_[data-slot=select-content]]:shadow-md',
            '[&_[data-slot=select-content][hidden]]:hidden',
            '[&_[data-slot=select-option]]:grid',
            '[&_[data-slot=select-option]]:min-h-9',
            '[&_[data-slot=select-option]]:grid-cols-[1rem_minmax(0,1fr)]',
            '[&_[data-slot=select-option]]:items-center',
            '[&_[data-slot=select-option]]:gap-2',
            '[&_[data-slot=select-option]]:rounded-sm',
            '[&_[data-slot=select-option]]:px-2',
            '[&_[data-slot=select-option]]:py-1.5',
            '[&_[data-slot=select-option]]:select-none',
            '[&_[data-slot=select-option]]:cursor-pointer',
            '[&_[data-slot=select-option][data-active]]:bg-accent',
            '[&_[data-slot=select-option][data-active]]:text-accent-foreground',
            '[&_[data-slot=select-option][data-disabled]]:pointer-events-none',
            '[&_[data-slot=select-option][data-disabled]]:cursor-not-allowed',
            '[&_[data-slot=select-option][data-disabled]]:opacity-50',
            '[&_[data-slot=select-option-label]]:min-w-0',
            '[&_[data-slot=select-option-label]]:break-words',
            '[&_[data-slot=select-option-indicator]]:h-1.5',
            '[&_[data-slot=select-option-indicator]]:w-2.5',
            '[&_[data-slot=select-option-indicator]]:border-b-2',
            '[&_[data-slot=select-option-indicator]]:border-l-2',
            '[&_[data-slot=select-option-indicator]]:border-current',
            '[&_[data-slot=select-option-indicator]]:opacity-0',
            '[&_[data-slot=select-option-indicator]]:[transform:translateY(-1px)_rotate(-45deg)]',
            '[&_[data-slot=select-option][data-state=checked]_[data-slot=select-option-indicator]]:opacity-100',
            '[&_[data-slot=select-message]]:mt-1',
            '[&_[data-slot=select-message]]:text-sm',
            '[&_[data-slot=select-message]]:text-destructive',
            '[&_[data-slot=select-message]:empty]:hidden',
            'data-[state=open]:[&_[data-slot=select-trigger]]:ring-1',
            'data-[state=open]:[&_[data-slot=select-trigger]]:ring-ring',
            'data-[state=open]:[&_[data-slot=select-indicator]]:[transform:translateY(2px)_rotate(225deg)]',
            'data-[side=top]:[&_[data-slot=select-content]]:top-auto',
            'data-[side=top]:[&_[data-slot=select-content]]:bottom-[calc(100%+0.25rem)]',
            'data-[size=sm]:[&_[data-slot=select-trigger]]:h-8',
            'data-[size=sm]:[&_[data-slot=select-trigger]]:px-2.5',
            'data-[size=sm]:[&_[data-slot=select-trigger]]:text-xs',
            'data-[size=lg]:[&_[data-slot=select-trigger]]:h-10',
            'data-[size=lg]:[&_[data-slot=select-trigger]]:px-4',
            'data-[invalid]:[&_[data-slot=select-trigger]]:border-destructive',
            'data-[invalid]:[&_[data-slot=select-trigger]]:focus-visible:ring-destructive',
            'data-[disabled]:cursor-not-allowed',
            'data-[disabled]:opacity-50',
            '[&_[data-slot=select-trigger]]:disabled:cursor-not-allowed',
          ].join(' '),
          className,
        )}
        {...props}
      />
    )
  },
)

Select.displayName = 'Select'
