import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import pc from 'picocolors'

interface RequiredDoc {
  path: string
  mustContain: string[]
}

const root = process.cwd()
const docsRoot = resolve(root, 'apps/docs')

const componentDocs = [
  'button',
  'input',
  'checkbox',
  'switch',
  'tabs',
  'dialog',
  'label',
  'textarea',
  'radio-group',
  'select',
  'card',
  'badge',
  'separator',
  'skeleton',
  'alert',
  'collapsible',
  'accordion',
  'tooltip',
  'progress',
  'avatar',
]

const requiredDocs: RequiredDoc[] = [
  {
    path: 'index.md',
    mustContain: ['Zeus Web', 'pnpm dlx @zeus-web/cli init'],
  },
  {
    path: 'guide/getting-started.md',
    mustContain: [
      '# Getting Started',
      'pnpm dlx @zeus-web/cli init',
      'pnpm dlx @zeus-web/cli add button input',
    ],
  },
  {
    path: 'guide/cli.md',
    mustContain: ['# CLI', 'zweb init', 'zweb add', 'zweb ai'],
  },
  {
    path: 'guide/theming.md',
    mustContain: ['# Theming', 'default', 'slate', 'zinc', 'neutral', 'stone'],
  },
  {
    path: 'guide/registry.md',
    mustContain: ['# Registry', '@zeus-web/registry', 'registry.json'],
  },
  {
    path: 'guide/ai.md',
    mustContain: ['# AI', '@zeus-web/ai', 'zweb ai --cursor'],
  },
  {
    path: 'components/index.md',
    mustContain: [
      'This file is generated by scripts/commands/generate-docs.ts',
      '# Components',
      '@zeus-web/ai',
      '@zeus-web/registry',
    ],
  },
  {
    path: 'examples/react-vite.md',
    mustContain: ['# React Vite Example', '@zeus-web/example-react-vite'],
  },
  {
    path: 'examples/next-app.md',
    mustContain: [
      '# Next.js App Router Example',
      '@zeus-web/example-next-app',
      '@zeus-web/button/react',
      "'use client'",
    ],
  },
  {
    path: 'examples/native-wc.md',
    mustContain: [
      '# Native Web Components Example',
      '@zeus-web/example-native-wc',
    ],
  },
  {
    path: 'playground/index.md',
    mustContain: [
      '# Interactive Playground',
      '<ZeusPlayground />',
      '@zeus-web/<component>/wc imports',
    ],
  },
]

const forbiddenPatterns = [
  {
    pattern: '@zeus-ui',
    message: 'old @zeus-ui package scope must not appear in docs',
  },
  {
    pattern: 'zeus-ui',
    message: 'old zeus-ui name must not appear in docs content',
  },
]

function filePath(relativePath: string): string {
  return resolve(docsRoot, relativePath)
}

function checkFileExists(relativePath: string): string[] {
  const file = filePath(relativePath)
  if (!existsSync(file)) return [`Missing docs file: apps/docs/${relativePath}`]
  return []
}

function checkForbiddenPatterns(path: string, source: string): string[] {
  const errors: string[] = []
  for (const item of forbiddenPatterns) {
    if (source.includes(item.pattern))
      errors.push(`apps/docs/${path}: ${item.message}`)
  }
  return errors
}

function checkRequiredContent(doc: RequiredDoc): string[] {
  const errors: string[] = []
  const source = readFileSync(filePath(doc.path), 'utf-8')
  for (const text of doc.mustContain) {
    if (!source.includes(text))
      errors.push(`apps/docs/${doc.path} must contain "${text}"`)
  }
  errors.push(...checkForbiddenPatterns(doc.path, source))
  return errors
}

function checkVitePressConfig(): string[] {
  const configPath = filePath('.vitepress/config.ts')
  const siteDataPath = filePath('.vitepress/data/site.ts')
  const errors: string[] = []

  if (!existsSync(configPath)) return ['Missing apps/docs/.vitepress/config.ts']
  if (!existsSync(siteDataPath))
    return ['Missing apps/docs/.vitepress/data/site.ts']

  const configSource = readFileSync(configPath, 'utf-8')
  const siteSource = readFileSync(siteDataPath, 'utf-8')

  for (const text of [
    "import { defineConfig } from 'vitepress'",
    "import { sidebar, topNav } from './data/site'",
    'nav: topNav',
    'sidebar',
  ]) {
    if (!configSource.includes(text))
      errors.push(`VitePress config must contain "${text}"`)
  }

  for (const route of [
    '/guide/getting-started',
    '/components/',
    ...componentDocs.map(c => `/components/${c}`),
    '/playground/',
    '/examples/react-vite',
    '/examples/next-app',
    '/examples/native-wc',
  ]) {
    if (!siteSource.includes(route))
      errors.push(`data/site.ts must contain route "${route}"`)
  }

  return errors
}

function checkDocsTheme(): string[] {
  return [
    '.vitepress/theme/index.ts',
    '.vitepress/theme/style.css',
    '.vitepress/data/site.ts',
  ].flatMap(file => checkFileExists(file))
}

function checkComponentDocsErrors(components: string[]): string[] {
  const errors: string[] = []

  for (const component of components) {
    const relativePath = `components/${component}.md`
    const file = filePath(relativePath)

    if (!existsSync(file)) {
      errors.push(`Missing generated component doc: ${relativePath}`)
      continue
    }

    const source = readFileSync(file, 'utf-8')

    if (
      !source.includes(
        'This file is generated by scripts/commands/generate-docs.ts',
      )
    ) {
      errors.push(`${relativePath} must be generated`)
    }

    if (!source.includes(`zweb add ${component}`)) {
      errors.push(`${relativePath} must document zweb add ${component}`)
    }

    if (!source.includes(`@zeus-web/${component}/react`)) {
      errors.push(`${relativePath} must document @zeus-web/${component}/react`)
    }

    if (!source.includes(`@zeus-web/${component}/wc`)) {
      errors.push(`${relativePath} must document @zeus-web/${component}/wc`)
    }

    if (!source.includes(`@/components/ui/${component}`)) {
      errors.push(`${relativePath} must document @/components/ui/${component}`)
    }

    errors.push(...checkForbiddenPatterns(relativePath, source))
  }

  return errors
}

function checkGeneratedComponentDocs(): string[] {
  return checkComponentDocsErrors(componentDocs)
}

function main(): void {
  const errors: string[] = []

  for (const doc of requiredDocs) {
    errors.push(...checkFileExists(doc.path))
    if (existsSync(filePath(doc.path)))
      errors.push(...checkRequiredContent(doc))
  }

  errors.push(...checkVitePressConfig())
  errors.push(...checkDocsTheme())
  errors.push(...checkGeneratedComponentDocs())

  if (errors.length > 0) {
    console.error(pc.red('Docs contract check failed:'))
    for (const error of errors) console.error(`- ${error}`)
    process.exit(1)
  }

  console.log(pc.green('Docs contract check passed.'))
}

main()
