import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { basename, resolve } from 'node:path'

import pc from 'picocolors'

import { generateComponentDocs } from '../../docs/component-docs'
import { formatGeneratedDocs } from '../../docs/format-generated-docs'

async function main(): Promise<void> {
  const errors: string[] = []
  const docs = await formatGeneratedDocs(generateComponentDocs())
  const generatedPaths = new Set(docs.map(doc => doc.path))

  for (const doc of docs) {
    const file = resolve(process.cwd(), doc.path)

    if (!existsSync(file)) {
      errors.push(`Missing generated doc: ${doc.path}`)
      continue
    }

    const current = readFileSync(file, 'utf-8')

    if (current !== doc.content) {
      errors.push(`Generated doc is out of date: ${doc.path}`)
    }
  }

  const componentsDir = resolve(process.cwd(), 'apps/docs/components')

  if (existsSync(componentsDir)) {
    for (const entry of readdirSync(componentsDir, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith('.md')) continue

      const docPath = `apps/docs/components/${entry.name}`

      if (!generatedPaths.has(docPath)) {
        errors.push(
          `Stale generated component doc exists but is no longer generated: ${docPath}`,
        )
      }

      const source = readFileSync(resolve(componentsDir, entry.name), 'utf-8')

      if (
        source.includes(
          'This file is generated by scripts/commands/generate-docs.ts',
        ) &&
        !generatedPaths.has(docPath)
      ) {
        errors.push(
          `Remove stale generated component doc: ${basename(docPath)}`,
        )
      }
    }
  }

  if (errors.length > 0) {
    console.error(pc.red('Generated docs check failed:'))

    for (const error of errors) {
      console.error(`- ${error}`)
    }

    console.error('')
    console.error('Run:')
    console.error('  pnpm docs:generate')
    process.exit(1)
  }

  console.log(pc.green('Generated docs check passed.'))
}

main().catch(error => {
  console.error(pc.red((error as Error).message))
  console.error(error)
  process.exit(1)
})
