import type { ComponentCatalogItem } from '../../../apps/docs/.vitepress/data/component-catalog'
import type { Registry } from '../../../packages/registry/src'

import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import pc from 'picocolors'

import { componentCatalog } from '../../../apps/docs/.vitepress/data/component-catalog'

interface RequiredDoc {
  path: string
  mustContain: string[]
}

const root = process.cwd()
const docsRoot = resolve(root, 'apps/docs')

const componentDocs = componentCatalog

function loadRegistry(): Registry {
  return JSON.parse(
    readFileSync(resolve(root, 'packages/registry/registry.json'), 'utf-8'),
  ) as Registry
}

function getRegistryComponentNames(): Set<string> {
  const items = loadRegistry().items.filter(item => item.type === 'component')

  return new Set(items.map(item => item.name))
}

const requiredDocs: RequiredDoc[] = [
  {
    path: 'index.md',
    mustContain: [
      'Zeus Web',
      'CLI registry source',
      '@zeus-web/ui',
      'pnpm dlx @zeus-web/cli init',
    ],
  },
  {
    path: 'guide/getting-started.md',
    mustContain: [
      '# Getting Started',
      'zeus-ui.json',
      'src/lib/cn.ts',
      'src/styles/zeus.css',
      'pnpm dlx @zeus-web/cli init',
      'pnpm dlx @zeus-web/cli add button input',
      "import '@zeus-web/ui'",
      '@zeus-web/button/react',
    ],
  },
  {
    path: 'guide/usage-modes.md',
    mustContain: [
      '# Usage Modes',
      'CLI registry source',
      'Native styled Web Components',
      'Advanced primitives',
      '@zeus-web/ui',
      '@zeus-web/button/react',
    ],
  },
  {
    path: 'guide/cli.md',
    mustContain: [
      '# CLI',
      'zweb init',
      'zweb add',
      'zeus-ui.json',
      'src/lib/cn.ts',
      'src/styles/zeus.css',
      'zeus-ui.lock.json',
      'zweb ai',
    ],
  },
  {
    path: 'guide/theming.md',
    mustContain: [
      '# Theming',
      '--zeus-*',
      '--zw-*',
      'default',
      'slate',
      'zinc',
      'neutral',
      'stone',
      'src/styles/zeus.css',
    ],
  },
  {
    path: 'guide/registry.md',
    mustContain: [
      '# Registry',
      '@zeus-web/registry',
      'registry.json',
      'registryDependencies',
      'templates/react/button.tsx',
      'templates/vue/button.vue',
      'zeus-ui.json',
    ],
  },
  {
    path: 'guide/ai.md',
    mustContain: ['# AI', '@zeus-web/ai', 'zweb ai --cursor'],
  },
  {
    path: 'guide/icons.md',
    mustContain: [
      '# Icons',
      '@zeus-web/icons',
      '@zeus-web/icons/react',
      '@zeus-web/icons/vue',
      '@zeus-web/icons/wc',
      'zweb icon list',
    ],
  },
  {
    path: 'components/index.md',
    mustContain: [
      'This file is generated by scripts/commands/generate-docs.ts',
      '# Components',
      '<ComponentDirectory />',
      '25 public component packages',
      'Current registry components',
      'Advanced components are installed from their package.',
    ],
  },
  {
    path: 'components/data-grid.md',
    mustContain: [
      '# Data Grid',
      '<DataGridPlayground />',
      '100,000 rows',
      '1,000 columns',
      '[Web Component]',
      '[React]',
      '[Vue]',
    ],
  },
  {
    path: 'examples/react-vite.md',
    mustContain: ['# React Vite Example', '@zeus-web/example-react-vite'],
  },
  {
    path: 'examples/next-app.md',
    mustContain: [
      '# Next.js App Router Example',
      '@zeus-web/example-next-app',
      '@zeus-web/button/react',
      "'use client'",
      'zeus-ui.json',
    ],
  },
  {
    path: 'examples/native-wc.md',
    mustContain: [
      '# Native Web Components Example',
      '@zeus-web/ui',
      'pnpm showcase:native',
      "import '@zeus-web/ui'",
      "import '@zeus-web/button/wc/auto'",
    ],
  },
]

const requiredChineseDocs: RequiredDoc[] = [
  {
    path: 'zh/index.md',
    mustContain: ['Zeus Web', '开始使用', '/zh/guide/getting-started'],
  },
  {
    path: 'zh/guide/getting-started.md',
    mustContain: ['# 开始使用', 'zeus-ui.json', '@zeus-web/button/react'],
  },
  {
    path: 'zh/guide/usage-modes.md',
    mustContain: ['# 使用模式', '@zeus-web/ui', '@zeus-web/button/react'],
  },
  {
    path: 'zh/guide/cli.md',
    mustContain: ['# CLI', 'zweb init', 'zweb add'],
  },
  {
    path: 'zh/guide/theming.md',
    mustContain: ['# 主题', '--zeus-*', 'src/styles/zeus.css'],
  },
  {
    path: 'zh/guide/icons.md',
    mustContain: ['# 图标', '@zeus-web/icons/react', 'zweb icon list'],
  },
  {
    path: 'zh/guide/registry.md',
    mustContain: ['# Registry', '@zeus-web/registry', 'registry.json'],
  },
  {
    path: 'zh/guide/ai.md',
    mustContain: ['# AI', '@zeus-web/ai', 'zweb ai --cursor'],
  },
  {
    path: 'zh/examples/react-vite.md',
    mustContain: ['# React Vite 示例', '@zeus-web/example-react-vite'],
  },
  {
    path: 'zh/examples/next-app.md',
    mustContain: [
      '# Next.js App Router 示例',
      '@zeus-web/example-next-app',
      '1. 本地 `src/components/ui/*` 组件。',
      '2. 通过 `@zeus-web/button/react` 等路径按组件导入 React wrapper。',
      '3. 使用 `"use client"` 声明 Client Component 边界。',
      '4. 通过 `@zeus-web/themes/default.css` 导入主题。',
      '5. 使用 `zeus-ui.json` 配置路径别名。',
    ],
  },
  {
    path: 'zh/examples/native-wc.md',
    mustContain: ['# 原生 Web Components 示例', '@zeus-web/ui'],
  },
]

const forbiddenPatterns = [
  {
    pattern: '@zeus-ui',
    message: 'old @zeus-ui package scope must not appear in docs',
  },
  {
    pattern: '@zeus-web/react',
    message: 'old aggregate @zeus-web/react package must not appear in docs',
  },
  {
    pattern: '@zeus-web/vue',
    message: 'old aggregate @zeus-web/vue package must not appear in docs',
  },
  {
    pattern: '@zeus-web/headless',
    message: 'old aggregate @zeus-web/headless package must not appear in docs',
  },
  {
    pattern: 'components.json',
    message: 'old components.json config must not appear in public docs',
  },
  {
    pattern: 'src/styles/globals.css',
    message: 'old globals.css config path must not appear in public docs',
  },
  {
    pattern: 'src/lib/utils.ts',
    message:
      'old utils.ts registry utility path must not appear in public docs',
  },
  {
    pattern: 'registry:ui',
    message: 'old registry:ui schema must not appear in public docs',
  },
  {
    pattern: 'registry:lib',
    message: 'old registry:lib schema must not appear in public docs',
  },
  {
    pattern: 'default/lib/utils.ts',
    message: 'old default/lib/utils.ts path must not appear in public docs',
  },
]

function filePath(relativePath: string): string {
  return resolve(docsRoot, relativePath)
}

function checkFileExists(relativePath: string): string[] {
  const file = filePath(relativePath)
  if (!existsSync(file)) return [`Missing docs file: apps/docs/${relativePath}`]
  return []
}

function checkForbiddenPatterns(path: string, source: string): string[] {
  const errors: string[] = []

  for (const item of forbiddenPatterns) {
    if (source.includes(item.pattern)) {
      errors.push(`apps/docs/${path}: ${item.message}`)
    }
  }

  return errors
}

function checkRequiredContent(doc: RequiredDoc): string[] {
  const errors: string[] = []
  const source = readFileSync(filePath(doc.path), 'utf-8')

  for (const text of doc.mustContain) {
    if (!source.includes(text)) {
      errors.push(`apps/docs/${doc.path} must contain "${text}"`)
    }
  }

  errors.push(...checkForbiddenPatterns(doc.path, source))
  return errors
}

function checkVitePressConfig(): string[] {
  const configPath = filePath('.vitepress/config.ts')
  const siteDataPath = filePath('.vitepress/data/site.ts')
  const catalogPath = filePath('.vitepress/data/component-catalog.ts')
  const errors: string[] = []

  if (!existsSync(configPath)) return ['Missing apps/docs/.vitepress/config.ts']
  if (!existsSync(siteDataPath)) {
    return ['Missing apps/docs/.vitepress/data/site.ts']
  }
  if (!existsSync(catalogPath)) {
    return ['Missing apps/docs/.vitepress/data/component-catalog.ts']
  }

  const configSource = readFileSync(configPath, 'utf-8')
  const siteSource = readFileSync(siteDataPath, 'utf-8')
  const catalogSource = readFileSync(catalogPath, 'utf-8')

  for (const text of [
    "import { defineConfig } from 'vitepress'",
    "from './data/docs-i18n'",
    "from './data/site'",
    "logo: '/logo.svg'",
    'locales: {',
    'root: {',
    'zh: {',
    'i18nRouting: true',
  ]) {
    if (!configSource.includes(text)) {
      errors.push(`VitePress config must contain "${text}"`)
    }
  }

  for (const route of [
    '/guide/getting-started',
    '/guide/usage-modes',
    '/guide/cli',
    '/guide/theming',
    '/guide/icons',
    '/components/',
    '/examples/react-vite',
    '/examples/next-app',
    '/examples/native-wc',
  ]) {
    if (!siteSource.includes(route)) {
      errors.push(`data/site.ts must contain route "${route}"`)
    }
  }

  for (const text of [
    'getComponentCatalog',
    'getComponentCategories',
    'localizeDocsPath',
  ]) {
    if (!siteSource.includes(text)) {
      errors.push(
        `data/site.ts must derive localized navigation from "${text}"`,
      )
    }
  }

  if (!catalogSource.includes('componentIdentities')) {
    errors.push(
      'component-catalog.ts must keep locale-neutral component identities',
    )
  }

  for (const text of ["title: 'Button'", "title: '按钮'"]) {
    if (!catalogSource.includes(text)) {
      errors.push(`component-catalog.ts must contain localized copy "${text}"`)
    }
  }

  return errors
}

function checkDocsTheme(): string[] {
  return [
    '.vitepress/theme/index.ts',
    '.vitepress/theme/style.css',
    '.vitepress/theme/components/ComponentDirectory.vue',
    '.vitepress/data/component-catalog.ts',
    '.vitepress/data/site.ts',
  ].flatMap(file => checkFileExists(file))
}

function checkComponentDocsErrors(
  components: readonly ComponentCatalogItem[],
): string[] {
  const errors: string[] = []
  const registryComponents = getRegistryComponentNames()

  for (const component of components) {
    const relativePath = `components/${component.name}.md`
    const file = filePath(relativePath)

    if (!existsSync(file)) {
      errors.push(`Missing generated component doc: ${relativePath}`)
      continue
    }

    const source = readFileSync(file, 'utf-8')

    if (
      !source.includes(
        'This file is generated by scripts/commands/generate-docs.ts',
      )
    ) {
      errors.push(`${relativePath} must be generated`)
    }

    if (!source.includes(`${component.packageName}/react`)) {
      errors.push(
        `${relativePath} must document ${component.packageName}/react`,
      )
    }

    if (!source.includes(`${component.packageName}/wc/auto`)) {
      errors.push(
        `${relativePath} must document ${component.packageName}/wc/auto`,
      )
    }

    if (!source.includes(`${component.packageName}/vue`)) {
      errors.push(`${relativePath} must document ${component.packageName}/vue`)
    }

    const playgroundMarkup =
      component.name === 'data-grid'
        ? '<DataGridPlayground />'
        : `<ComponentPlayground name="${component.name}" />`

    if (
      !source.includes('## Playground') ||
      !source.includes(playgroundMarkup)
    ) {
      errors.push(
        `${relativePath} must embed its interactive Playground using "${playgroundMarkup}"`,
      )
    }

    if (source.includes('/playground/')) {
      errors.push(
        `${relativePath} must not link to a standalone Playground route`,
      )
    }

    if (component.packageGroup === 'advanced') {
      if (!source.includes(`pnpm add ${component.packageName}`)) {
        errors.push(
          `${relativePath} must document installing ${component.packageName}`,
        )
      }

      if (
        !source.includes('## Component family') ||
        !source.includes('## Methods')
      ) {
        errors.push(
          `${relativePath} must document its advanced component family and methods`,
        )
      }
    } else if (registryComponents.has(component.name)) {
      if (!source.includes(`zweb add ${component.name}`)) {
        errors.push(`${relativePath} must document zweb add ${component.name}`)
      }

      if (!source.includes(`@/components/ui/${component.name}`)) {
        errors.push(
          `${relativePath} must document @/components/ui/${component.name}`,
        )
      }

      if (!source.includes('Registry source: available.')) {
        errors.push(`${relativePath} must document registry availability`)
      }
    } else if (component.packageGroup === 'primitives') {
      if (!source.includes('Registry source: not available yet.')) {
        errors.push(`${relativePath} must document missing registry source`)
      }

      for (const localePrefix of ['', 'zh/']) {
        const localizedPath = `${localePrefix}components/${component.name}.md`
        const localizedFile = filePath(localizedPath)

        if (!existsSync(localizedFile)) continue

        const localizedSource = readFileSync(localizedFile, 'utf-8')

        if (localizedSource.includes(`@/components/ui/${component.name}`)) {
          errors.push(
            `${localizedPath} must not document unavailable registry import @/components/ui/${component.name}`,
          )
        }

        if (localizedSource.includes(`zweb add ${component.name}`)) {
          errors.push(
            `${localizedPath} must not document unavailable command zweb add ${component.name}`,
          )
        }
      }
    }

    errors.push(...checkForbiddenPatterns(relativePath, source))
  }

  return errors
}

function main(): void {
  const errors: string[] = []

  for (const doc of requiredDocs.concat(requiredChineseDocs)) {
    errors.push(...checkFileExists(doc.path))
    if (errors.length === 0 || existsSync(filePath(doc.path))) {
      errors.push(...checkRequiredContent(doc))
    }
  }

  errors.push(...checkDocsTheme())
  errors.push(...checkVitePressConfig())
  errors.push(...checkComponentDocsErrors(componentDocs))

  if (errors.length > 0) {
    console.error(pc.red('Docs check failed:'))

    for (const error of errors) console.error(`- ${error}`)

    process.exit(1)
  }

  console.log(pc.green('Docs check passed.'))
}

main()
